name: citmatel_strawberry_hangman
description: Hangman module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 1.1.0-RELEASE.20220301

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.1
  clean_core: ^1.2.3-RELEASE.20220206
  tuple: ^2.0.0

  # Visual & Animations
  animations: ^2.0.2
  page_view_indicators: ^2.0.0
  flutter_svg: ^1.0.3
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.13.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^10.1.0
  flutter_spinkit: ^5.1.0
  flutter_animator: ^3.2.1
  cupertino_icons: ^1.0.4
  tutorial_coach_mark: ^1.2.1
  confetti: ^0.6.0
  decorated_icon: ^1.2.1

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.4.0
  objectbox_flutter_libs: ^1.4.0
  path_provider: ^2.0.3
  flat_buffers: ^2.0.5
  clean_repo_objectbox: ^0.2.1-SNAPSHOT.20220223

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: ^1.4.0

flutter:
  assets:
    #Images
    - packages/citmatel_strawberry_hangman/assets/images/background.png

    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/1-lluvia.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/2-suelo.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/3-contaminar.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/4-sequía.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/5-derrumbe.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/6-deshecho.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/7-erosión.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/8-huracán.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/9-ahorrar.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/10-surcos.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/11-frutas.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/12-vaca.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/13-pozo.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/14-campesino.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/15-riego.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/16-postura.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/17-fumigar.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/18-terrazas.JPG
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/19-fértil.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/20-raices.jpg

    - packages/citmatel_strawberry_hangman/assets/niveles/tutorial/tutorial.png

  uses-material-design: true
