name: citmatel_strawberry_hangman
description: Hangman module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 0.2.0-SNAPSHOT.20220120

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.2.1-SNAPSHOT.20220116

  # Visual & Animations
  animations: ^2.0.2
  page_view_indicators: ^2.0.0
  flutter_svg: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.13.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  flutter_animator: ^3.2.0
  cupertino_icons: ^1.0.2
  tutorial_coach_mark: ^1.2.1
  confetti: ^0.6.0

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.3
  clean_repo_objectbox: 0.1.2-SNAPSHOT.20220116

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: any

flutter:
  assets:
    - packages/citmatel_strawberry_hangman/assets/icons/brain_in_blue.jpg
    - packages/citmatel_strawberry_hangman/assets/icons/hangman_wallpaper.jpg
    - packages/citmatel_strawberry_hangman/assets/level1/tutorial.jpg
    - packages/citmatel_strawberry_hangman/assets/level2/conferencia.png
    - packages/citmatel_strawberry_hangman/assets/level2/escuela.png
    - packages/citmatel_strawberry_hangman/assets/level2/graduacion.png
    - packages/citmatel_strawberry_hangman/assets/level2/escribir.jpg
    - packages/citmatel_strawberry_hangman/assets/level2/examen.jpg
    - packages/citmatel_strawberry_hangman/assets/level2/laboratorio.jpg
    - packages/citmatel_strawberry_hangman/assets/level2/libros.jpg
    - packages/citmatel_strawberry_hangman/assets/level2/notas.jpg
    

  uses-material-design: true
