name: citmatel_strawberry_hangman
description: Hangman module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 0.2.0-SNAPSHOT.20220120

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.2.3-RELEASE.20220206
  tuple: ^2.0.0

  # Visual & Animations
  animations: ^2.0.2
  page_view_indicators: ^2.0.0
  flutter_svg: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.13.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  flutter_animator: ^3.2.0
  cupertino_icons: ^1.0.2
  tutorial_coach_mark: ^1.2.1
  confetti: ^0.6.0
  decorated_icon: ^1.2.1

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.3
  clean_repo_objectbox: ^0.1.4-RELEASE.20220206

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: any

flutter:
  assets:
    #Images
    - packages/citmatel_strawberry_hangman/assets/images/background.png

    - packages/citmatel_strawberry_hangman/assets/niveles/ciencias-naturales/palma.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/ciencias-naturales/vacuna.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/ciencias-naturales/invierno.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/ciencias-naturales/nubes.jpg

    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/cheque.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/dinero.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/diploma.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/escribir.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/escuela.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/examen.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/libros.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/notas.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/ajedrés.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/almacén.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/granja.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/oficina.jpg

    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/1-cupido.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/2-grifo.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/3-hades.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/4-afrodita.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/5-anubis.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/6-pegaso.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/7-poseidón.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/8-fénix.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/9-ares.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/10-medusa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/11-artemisa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/12-fauno.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/13-apolo.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/14-centauro.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/15-hermes.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/16-sirena.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/17-dionisio.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/18-faraón.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/19-cerbero.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/20-deméter.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/21-hipogrifo.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/22-atena.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/23-cíclope.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/24-papiro.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/25-zeus.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/26-unicornio.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/27-hefesto.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/28-hidra.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/29-hera.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/30-sátiro.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/31-mantícora.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/32-basilisco.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/33-dragón.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/34-equidna.png

    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/1-laptop.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/2-robot.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/3-móvil.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/4-correo.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/5-impresora.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/6-cohete.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/7-clave.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/8-memoria.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/9-virus.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/10-video.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/11-código.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/12-huella.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/13-chat.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/14-aguja.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/15-gráficos.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/16-latidos.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/17-control.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/18-drone.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/19-disco.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/20-juego.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/21-adaptador.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/22-monitor.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/23-minar.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/24-lector.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/25-transferir.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/26-cámara.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/27-pago.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/28-metaverso.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/29-almacenar.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/30-bocina.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/31-teclado.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/32-consola.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/33-aplicación.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/34-reproductor.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/35-reloj.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/36-ram.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/37-altavoz.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/38-conector.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/39-placa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/40-filtrar.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/41-satélite.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/42-procesador.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/43-latiguillo.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/44-micro-sd.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/45-fan.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/46-antena.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/47-cassete.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/48-wifi.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/49-corriente.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/50-hdmi.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/51-mouse.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/52-tableta.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/53-holograma.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/54-vga.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/55-psp.png
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/56-enrutador.png

    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/1-américa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/2-china.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/3-rusia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/4-isla.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/5-hungría.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/6-brújula.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/7-cuba.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/8-lago.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/9-croacia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/10-chile.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/11-canadá.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/12-áfrica.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/13-egipto.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/14-suecia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/15-rosa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/16-polonia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/17-perú.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/18-portugal.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/19-moscú.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/20-islandia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/21-turquía.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/22-irán.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/23-india.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/24-gales.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/25-paraguay.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/26-rumanía.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/27-argentina.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/28-siria.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/29-alemania.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/30-japón.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/31-albania.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/32-tailandia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/33-australia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/34-londres.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/35-argelia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/36-italia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/37-brasil.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/38-cascada.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/39-checa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/40-austria.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/41-eeuu.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/42-europa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/43-bélgica.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/44-españa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/45-sudáfrica.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/46-suiza.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/47-málaga.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/48-francia.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/49-toscana.png
    - packages/citmatel_strawberry_hangman/assets/niveles/geografía/50-finlandia.png

    - packages/citmatel_strawberry_hangman/assets/niveles/tutorial/tutorial.jpg

  uses-material-design: true
