name: citmatel_strawberry_hangman
description: Hangman module for CITMATEL's 'strawberry' project

publish_to: 'none'

version: 0.1.0-SNAPSHOT.20211220

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.1.3-SNAPSHOT.20220109

  # Visual & Animations
  animations: ^2.0.2
  page_view_indicators: ^2.0.0
  flutter_svg: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.13.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  flutter_animator: ^3.2.0
  cupertino_icons: ^1.0.2

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:   
    - packages/citmatel_strawberry_hangman/assets/icons/brain_in_blue.jpg
    - packages/citmatel_strawberry_hangman/assets/icons/hangman_wallpaper.jpg

  uses-material-design: true