name: citmatel_strawberry_hangman
description: Hangman module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 0.2.0-SNAPSHOT.20220120

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.2.3-RELEASE.20220206
  tuple: ^2.0.0

  # Visual & Animations
  animations: ^2.0.2
  page_view_indicators: ^2.0.0
  flutter_svg: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.13.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  flutter_animator: ^3.2.0
  cupertino_icons: ^1.0.2
  tutorial_coach_mark: ^1.2.1
  confetti: ^0.6.0

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  path_provider: ^2.0.3
  clean_repo_objectbox: ^0.1.4-RELEASE.20220206

dev_dependencies:
  flutter_test:
    sdk: flutter

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: any

flutter:
  assets:
    #Images
    - packages/citmatel_strawberry_hangman/assets/images/background.png

    - packages/citmatel_strawberry_hangman/assets/niveles/ciencias-naturales/palma.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/ciencias-naturales/vacuna.jpg

    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/cheque.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/dinero.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/diploma.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/escribir.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/escuela.png
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/examen.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/libros.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/notas.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/ajedrés.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/almacén.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/granja.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/conoc-general/oficina.jpg

    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/anubis.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/faraón.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/fénix.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/ares.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/artemisa.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/deméter.png 
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/fauno.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/hades.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/hefesto.png
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/poseidón.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/mitología/zeus.jpg

    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/cohete.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/chat.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/clave.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/codigo.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/correo.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/juego.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/laptop.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/video.jpg
    - packages/citmatel_strawberry_hangman/assets/niveles/tecnologías/virus.jpg

    - packages/citmatel_strawberry_hangman/assets/niveles/tutorial/tutorial.jpg

  uses-material-design: true
