name: citmatel_strawberry_hangman
description: Hangman module for CITMATEL's 'strawberry' project

publish_to: 'none'

version: 0.0.1-SNAPSHOT.20211202

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true